---
galaxy_info:
  author: Harsimran Singh
  description: Role to get list of amis based on the filters passed.
  company: IGP
  license: GPL
  platforms:
    - name: Rocky Linux
      versions:
        - 8
        - 9
    - name: EL
      versions:
        - 7
        - 8
        - 9
dependencies: []