---
- name: Create Target group
  local_action:
     module: community.aws.elb_target_group
     name: "{{ tg_name }}"
     protocol: "{{ tg_protocol }}"
     port: "{{ tg_port }}"
     vpc_id: "{{ tg_vpc_id }}"
     health_check_protocol: "{{ tg_healthcheck_protocol }}"
     health_check_path: "{{ tg_healthcheck_path }}"
     health_check_port: "{{ tg_healthcheck_port }}"
     successful_response_codes: "{{ tg_healthcheck_success_response_code }}"
     health_check_interval: "{{ tg_healthcheck_interval }}"
     health_check_timeout: "{{ tg_healthcheck_timeout }}"
     healthy_threshold_count: "{{ tg_healthcheck_healthy_count }}"
     unhealthy_threshold_count: "{{ tg_healthcheck_unhealthy_count }}"
     deregistration_delay_timeout: "{{ tg_deregistration_delay_timeout }}"
     tags:
        Name: "{{ec2_tag_Name}}"
        environment: "{{ec2_tag_environment}}"
        cluster: "{{ec2_tag_cluster}}"
        app_version: "{{ec2_tag_app_version}}"
        service: "{{ec2_tag_service}}"
        team: "{{ec2_tag_team}}"
     state: present
     wait: true
     wait_timeout: 500
     region: "{{ tg_region }}"
  register: tg_arn
