---
galaxy_info:
  author: Manasi Naik
  description: Role for executing find_asg and if the latest asg has 0 instances then notify_to_gchat role will be executed.
  company: IGP
  license: GPL
  min_ansible_version: 2.0
dependencies: []