ec2_key_name: igp-prod-api
ec2_sg_id: "sg-2fa5af5d,sg-0f39cd8f51681479a"
processor_type: graviton
ec2_instance_type: t4g.small
termination_protection: "false"
graviton_ec2_ami_id: "ami-04ace70e7f6a09d4a"
intel_ec2_ami_id: "ami-08f362c39d03a4eb5"
ec2_subnet_id: subnet-0acc71da8e7560bdc
ec2_region: "us-east-1"
assign_public_ip: false
ec2_tag_Name: test-instance
ec2_tag_environment: "production"
ec2_tag_cluster: test-instance
ec2_tag_os: "rocky-linux-9"
ec2_tag_os_user: "rocky"
ec2_tag_ssh_port: "22"
ec2_tag_service: test-instance
ec2_tag_team: "devops"
ec2_tag_app_version: "no-version"
ec2_count: 1
ec2_volume_size: "50"
