---
galaxy_info:
  author: Harsimran Singh
  description: Role for creating AWS target group for IGP.
  company: IGP
  license: GPL
  platforms:
    - name: Rocky Linux
      versions:
        - 8
        - 9
    - name: EL
      versions:
        - 7
        - 8
        - 9
dependencies: []