# Generic Playbook for purging FE local cache
# Notes:
# Example invocation:
#   ansible-playbook -vvv /etc/ansible/playbooks/delete_fe_local_cache.yml -e purge_hosts="$purge_hosts" -e num_deploy_host=$num_deploy_host

- name: Remove local cache
  hosts: "{{purge_hosts}}"
  remote_user: "{{tags.os_user}}"
  become: yes
  vars:
    ansible_ssh_port: "{{tags.ssh_port}}"
    ansible_ssh_private_key_file: '/var/lib/jenkins/.ssh/newigpkeys/{{key_name}}.pem'
  serial: 3
  max_fail_percentage: 0
  tasks:
    - name: Removing cache files
      shell: sudo rm -rf /etc/json/themepage_*