# Generic Playbook for creating Autoscaling policy
# Notes:
#   - refresh_asg_instances_awscli --> Role for refreshing autoscaling group instances using awscli.
# Example invocation:
#   ansible-playbook -vvv /etc/ansible/playbooks/refresh_asg_instances_cron.yml -e service="$service" -e asg_region="$asg_region" -e instance_warmup="$instance_warmup" -e min_healthy_percentage="$min_healthy_percentage" -e scale_in_protected_instances:"Refresh"|"Ignore"|"Wait" -e standby_instances:"Terminate"|"Ignore"|"Wait" -e skip_matching:"true|false"

- hosts: "localhost"
  roles:
    - { role: "find_asg" }
    - { role: "refresh_asg_instances_awscli", asg_name: "{{ (asgs.results|sort(reverse=true, attribute='created_time')).0.auto_scaling_group_name }}" }

