- hosts: "{{cluster_name}}"
  remote_user: "{{ec2_tag_os_user}}"
  become: yes
  vars:
    ansible_ssh_port: "{{ ec2_tag_ssh }}"
    ansible_ssh_private_key_file: '~/.ssh/newigpkeys/{{ ec2_key_name }}'
  serial: "{{num_deploy_host}}"
  max_fail_percentage: 0

  pre_tasks:
  - name: Gathering ec2 facts
    action: ec2_facts
  - name: Instance De-register
    local_action:
      module: ec2_elb
      instance_id: "{{ ansible_ec2_instance_id }}"
      ec2_elbs: "{{ item }}"
      state: absent
      region: us-east-1
      wait: yes
    with_items: "{{ ec2_elbs_out }}"

  roles:
    - { role: "service_restart" }

  post_tasks:
  - name: Instance Register
    local_action:
      module: ec2_elb
      instance_id: "{{ ansible_ec2_instance_id }}"
      ec2_elbs: "{{ item }}"
      state: present
      region: us-east-1
      wait: yes
      wait_timeout: 60
    with_items: "{{ ec2_elbs_in }}"
